### ISSUE TITLE
"TextDecoder is not defined" on raspberry pi4

### ISSUE THREAD

**Issue by nicolespin** [digiassetX/digiasset_ipfs_metadata_server#6]
I got an error with following message on my raspberry pi4.
Version of Node and NPM are v10.24.0 and 5.8.0, respectively.
Is this a know issue?

> pi@raspberrypi:~/digiasset_ipfs_metadata_server $ node index.js
> 
> /home/pi/digiasset_ipfs_metadata_server/node_modules/multibase/src/util.js:3
> const textDecoder = new TextDecoder()
>                     ^
> 
> ReferenceError: TextDecoder is not defined
>     at Object.<anonymous> (/home/pi/digiasset_ipfs_metadata_server/node_modules/multibase/src/util.js:3:21)
>     at Module._compile (internal/modules/cjs/loader.js:778:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
>     at Module.load (internal/modules/cjs/loader.js:653:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
>     at Module.require (internal/modules/cjs/loader.js:692:17)
>     at require (internal/modules/cjs/helpers.js:25:18)
>     at Object.<anonymous> (/home/pi/digiasset_ipfs_metadata_server/node_modules/multibase/src/base.js:3:24)
>     at Module._compile (internal/modules/cjs/loader.js:778:30)
>

**Comment by mctrivia** [comment]
You need to update your version of node to 14.17.1

Here is an article I found on how to do it on raspberry pi:
https://medium.com/@thedyslexiccoder/how-to-update-nodejs-npm-on-a-raspberry-pi-4-da75cad4148c

**Comment by nicolespin** [comment]
Awesome! 
It works with the latest node (v16.4.0).
Thank you for your suggestion.
